prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: fast-ssd
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi
    
    additionalScrapeConfigs:
      - job_name: 'qanto-nodes'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - qanto-testnet
                - qanto-mainnet
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: qanto-node
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: instance
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: fast-ssd
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['alertname', 'cluster', 'service']
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 12h
        receiver: 'default'
        routes:
          - match:
              severity: critical
            receiver: pagerduty
          - match:
              severity: warning
            receiver: slack
      receivers:
        - name: 'default'
          webhook_configs:
            - url: 'http://alertmanager-webhook:9093/webhook'
        - name: 'pagerduty'
          pagerduty_configs:
            - service_key: 'YOUR_PAGERDUTY_KEY'
        - name: 'slack'
          slack_configs:
            - api_url: 'YOUR_SLACK_WEBHOOK_URL'
              channel: '#qanto-alerts'

grafana:
  adminPassword: "QantoAdmin2024!"
  persistence:
    enabled: true
    storageClassName: fast-ssd
    size: 20Gi
  
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'qanto'
          orgId: 1
          folder: 'Qanto'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/qanto
  
  dashboards:
    qanto:
      qanto-overview:
        json: |
          {
            "dashboard": {
              "title": "Qanto Network Overview",
              "panels": [
                {
                  "id": 1,
                  "title": "Active Nodes",
                  "type": "stat",
                  "targets": [
                    {
                      "expr": "count(up{job=\"qanto-nodes\"} == 1)"
                    }
                  ]
                },
                {
                  "id": 2,
                  "title": "Total Transactions",
                  "type": "graph",
                  "targets": [
                    {
                      "expr": "sum(rate(qanto_transactions_total[5m]))"
                    }
                  ]
                },
                {
                  "id": 3,
                  "title": "Block Height",
                  "type": "stat",
                  "targets": [
                    {
                      "expr": "max(qanto_block_height)"
                    }
                  ]
                },
                {
                  "id": 4,
                  "title": "Network TPS",
                  "type": "gauge",
                  "targets": [
                    {
                      "expr": "sum(rate(qanto_transactions_total[1m])) * 60"
                    }
                  ]
                }
              ]
            }
          }
