p2p_address = "/ip4/0.0.0.0/tcp/8001"
api_address = "127.0.0.1:8082"
peers = ["/ip4/52.5.135.12/tcp/30333"]
local_full_p2p_address = "/ip4/0.0.0.0/tcp/8001/p2p/12D3KooWG4qmqTY9gQz9SQAYyLWNbq7JskuoxEnEEqCGzDgzfk7F"
network_id = "qanto-local-testnet"
genesis_validator = "74fd2aae70ae8e0930b87a3dcb3b77f5b71d956659849f067360d3486604db41"
contract_address = "5a6a7d8f232bfc2e21f42177f8cd46d672bed53a04736da81d66306d6e9e6818"
target_block_time = 31
difficulty = 1
max_amount = 100000000000
use_gpu = false
zk_enabled = false
mining_threads = 4
num_chains = 32
mining_chain_id = 0

[logging]
level = "info"

[p2p]
heartbeat_interval = 500
mesh_n_low = 6
mesh_n = 8
mesh_n_high = 16
mesh_outbound_min = 4
