# Qanto Mainnet Configuration
# This configuration connects your local node to the Qanto mainnet bootnode
# Replace genesis_validator with your own node's public address

[network]
# Connect to the mainnet bootnode
peers = ["/ip4/3.80.56.18/tcp/30333"]

[node]
# Your node's public address - replace with your own
genesis_validator = "74fd2aae70ae8e0930b87a3dcb3b77f5b71d956659849f067360d3486604db41"

# Mainnet contract address
contract_address = "5a6a7d8f232bfc2e21f42177f8cd46d672bed53a04736da81d66306d6e9e6818"

# Network configuration
network_id = "qanto-mainnet"
p2p_address = "0.0.0.0:30333"
api_address = "127.0.0.1:8080"

# Mining configuration
mining_threads = 4
use_gpu = false
zk_enabled = true
target_block_time = 30
difficulty = 1000
num_chains = 4
mining_chain_id = 0

[logging]
level = "info"

[p2p]
heartbeat_interval = 1000
mesh_n_low = 4
mesh_n = 6
mesh_n_high = 12
mesh_outbound_min = 2