p2p_address = "/ip4/0.0.0.0/tcp/8001"
local_full_p2p_address = "/ip4/0.0.0.0/tcp/8001/p2p/12D3KooWJXhhf8xDm8XH1CSBjLbemw7H384NQZwuexiRvqqFgZhC"
api_address = "127.0.0.1:8081"
network_id = "qanto-local-testnet"
peers = []
genesis_validator = "2119707c4caf16139cfb5c09c4dcc9bf9cfe6808b571c108d739f49cc14793b9"
# Target time for a new block in MILLISECONDS. 31ms = ~32 blocks per second.
target_block_time = 31
difficulty = 2
max_amount = 10000000000
use_gpu = false
zk_enabled = false
mining_threads = 4
# Increased initial chains to maximize parallelism for high TPS.
num_chains = 32
mining_chain_id = 0

[logging]
level = "info"

[p2p]
# Heartbeat interval in MILLISECONDS for faster network reaction times.
heartbeat_interval = 500
mesh_n = 8
mesh_n_low = 6
mesh_n_high = 16
mesh_outbound_min = 4