p2p_address = "/ip4/0.0.0.0/tcp/8001"
local_full_p2p_address = "/ip4/0.0.0.0/tcp/8001/p2p/12D3KooWJXhhf8xDm8XH1CSBjLbemw7H384NQZwuexiRvqqFgZhC"
api_address = "127.0.0.1:8081"
network_id = "qanto-local-testnet"
peers = []
genesis_validator = "2119707c4caf16139cfb5c09c4dcc9bf9cfe6808b571c108d739f49cc14793b9"
target_block_time = 60000
difficulty = 2
max_amount = 10000000000
use_gpu = false
zk_enabled = false
mining_threads = 4
num_chains = 1
mining_chain_id = 0

[logging]
level = "info"

[p2p]
heartbeat_interval = 10000
mesh_n = 4
mesh_n_low = 2
mesh_n_high = 8
mesh_outbound_min = 2