p2p_address = "0.0.0.0:30333"
api_address = "127.0.0.1:8080"
peers = []
local_full_p2p_address = "0.0.0.0:30333/p2p/12D3KooWBUfMefQKJAkLZPAqXKRMiZ6LST4bdeZykEwovDsAdGAt"
network_id = "qanto-testnet"
genesis_validator = "ae527b01ffcb3baae0106fbb954acd184e02cb379a3319ff66d3cdfb4a63f9d3"
contract_address = "4a8d50f24c5ffec79ac665d123a3bdecacaa95f9f26751385a5a925c647bd394"
target_block_time = 30
difficulty = 1
max_amount = 21000000000
use_gpu = false
zk_enabled = true
mining_threads = 4
num_chains = 1
mining_chain_id = 0

[logging]
level = "info"

[p2p]
heartbeat_interval = 500
mesh_n_low = 6
mesh_n = 8
mesh_n_high = 16
mesh_outbound_min = 4
