version: '3.8'

services:
  qanto-node:
    image: qanto-node:production
    container_name: qanto-node
    ports:
      - "30333:30333"  # P2P
      - "9933:9933"    # RPC
      - "9944:9944"    # WebSocket
      - "8080:8080"    # HTTP API
    volumes:
      - qanto-data:/var/lib/qanto/data
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    networks:
      - qanto-network

  qanto-website:
    image: qanto-website:production
    container_name: qanto-website
    ports:
      - "80:80"
    depends_on:
      - qanto-node
    restart: unless-stopped
    networks:
      - qanto-network

volumes:
  qanto-data:

networks:
  qanto-network:
    driver: bridge
