version: '3.8'

services:
  qanto-node:
    build: .
    container_name: qanto-node
    restart: unless-stopped
    ports:
      - "8080:8080" # API Port
      - "4001:4001" # P2P Port

    volumes:
      - ./config.toml:/data/config.toml:ro # 'ro' for read-only
      - ./wallet.key:/data/wallet.key:ro # 'ro' for read-only
      - ./qantodag_db:/data/db

    environment:
      - RUST_LOG=qanto=info,saga=debug
      - RUST_BACKTRACE=1
