p2p_address = "/ip4/0.0.0.0/tcp/8001"
local_full_p2p_address = "/ip4/0.0.0.0/tcp/8001/p2p/12D3KooWMx9LWtKd7gDTRsVP4JUQtieJLXk88USS5mRV9XLfaKzU"
api_address = "127.0.0.1:8081"
peers = ["/ip4/34.126.103.74/tcp/8000/p2p/12D3KooWBR2BrEdiAQf7WvFMsY95imu9vuXUXo2fUoLsoqVavz95"]
genesis_validator = "2119707c4caf16139cfb5c09c4dcc9bf9cfe6808b571c108d739f49cc14793b9"
target_block_time = 6000
difficulty = 1000
max_amount = 10000000000
use_gpu = false
zk_enabled = false
mining_threads = 4
num_chains = 2
mining_chain_id = 0

[logging]
level = "info"

[p2p]
heartbeat_interval = 500
mesh_n = 4
mesh_n_low = 1
mesh_n_high = 8
