# ============================================================================
# Boot Node Configuration
# ============================================================================

replicaCount: 1

image:
  repository: ""  # Will be set by deployment script
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

# ============================================================================
# Service Configuration
# ============================================================================

service:
  type: LoadBalancer
  loadBalancerIP: ""  # Will be set to the reserved Elastic IP
  annotations:
    # Load balancer annotations for generic Kubernetes deployment
    # Remove AWS-specific annotations for NameCheap hosting
  
  ports:
    p2p:
      port: 26656
      targetPort: 26656
      protocol: TCP
    rpc:
      port: 26657
      targetPort: 26657
      protocol: TCP
    ws:
      port: 9944
      targetPort: 9944
      protocol: TCP
    api:
      port: 1317
      targetPort: 1317
      protocol: TCP
    grpc:
      port: 9090
      targetPort: 9090
      protocol: TCP

# ============================================================================
# StatefulSet Configuration
# ============================================================================

nodeSelector:
  workload: blockchain

tolerations:
  - key: blockchain
    operator: Equal
    value: "true"
    effect: NoSchedule

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - qanto-boot-node
          topologyKey: kubernetes.io/hostname

# ============================================================================
# Persistent Storage
# ============================================================================

persistence:
  enabled: true
  storageClass: "gp3"
  accessMode: ReadWriteOnce
  size: 20Gi
  mountPath: /data

# ============================================================================
# Resource Limits
# ============================================================================

resources:
  limits:
    cpu: 8000m
    memory: 8Gi
  requests:
    cpu: 4000m
    memory: 8Gi

# ============================================================================
# Health Checks
# ============================================================================

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  tcpSocket:
    port: 26656

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
  tcpSocket:
    port: 26656

# ============================================================================
# Security Context
# ============================================================================

podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

# ============================================================================
# Environment Variables
# ============================================================================

env:
  - name: CHAIN_ID
    value: "qanto-mainnet"
  - name: MONIKER
    value: "qanto-boot-node"
  - name: LOG_LEVEL
    value: "info"
  - name: NODE_KEY_PATH
    value: "/secrets/node-key/node_key.json"
  - name: GENESIS_FILE_PATH
    value: "/config/genesis/genesis.json"

# ============================================================================
# Secrets
# ============================================================================

secrets:
  nodeKey:
    name: qanto-boot-node-key
    key: node_key.json

# ============================================================================
# ConfigMaps
# ============================================================================

configMaps:
  genesis:
    name: qanto-genesis
    key: genesis.json
  config:
    name: qanto-config
    key: config.toml

# ============================================================================
# Node Configuration
# ============================================================================

config:
  chainType: "mainnet"
  rustLog: "info"
  validator: "false"
  bootnodes: ""
  additional: {}

# ============================================================================
# Service Account
# ============================================================================

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# ============================================================================
# Monitoring
# ============================================================================

monitoring:
  enabled: true
  serviceMonitor:
    enabled: false
    interval: 30s
    path: /metrics
    port: metrics
