# ===============================================================
# HyperChain :: Public Testnet Configuration Template
# ===============================================================

# --- P2P Networking ---
p2p_address = "0.0.0.0"
p2p_port = 10333
boot_nodes = [
	"/ip4/35.184.73.89/tcp/10333/p2p/PEER_ID_FROM_SEED_US",
	"/ip4/34.105.141.52/tcp/10333/p2p/PEER_ID_FROM_SEED_EU",
	"/ip4/35.247.188.7/tcp/10333/p2p/PEER_ID_FROM_SEED_ASIA"
]

# --- API Configuration ---
# The address for the RPC/REST API server to listen on.
api_address = "127.0.0.1" # Corrected from rpc_address
rpc_port = 9071

# --- Node Operation ---
db_path = "./hyperchain_db"
log_level = "info"

# --- Consensus Parameters ---
genesis_validator = "2119707c4caf16139cfb5c09c4dcc9bf9cfe6808b571c108d739f49cc14793b9"

# --- Mining Configuration ---
use_gpu = false
mining_threads = 4