p2p_address = "/ip4/0.0.0.0/tcp/8071"
peers = ["/ip4/127.0.0.1/tcp/8000/p2p/12D3KooWJXhhf8xDm8XH1CSBjLbemw7H384NQZwuexiRvqqFgZhC"]
api_address = "127.0.0.1:9071"
genesis_validator = "2119707c4caf16139cfb5c09c4dcc9bf9cfe6808b571c108d739f49cc14793b9"
target_block_time = 60000
difficulty = 100
max_amount = 10000000000
use_gpu = false
zk_enabled = false
mining_threads = 1
num_chains = 1
mining_chain_id = 0
network_id = "hyperdag-testnet"

[logging]
level = "info"

[p2p]
heartbeat_interval = 10000
mesh_n = 2
mesh_n_low = 1
mesh_n_high = 3