// The primary modules that define the Qanto node and its behavior.
pub mod adaptive_mining;
pub mod analytics_dashboard;
pub mod config;
pub mod config_validator;
pub mod consensus;
pub mod decentralization;
pub mod diagnostics;
pub mod emission;
pub mod graphql_server;
pub mod hame;
pub mod interoperability;
pub mod keygen;
pub mod mempool;
pub mod metrics;
pub mod miner;
pub mod mining_celebration;
pub mod mining_metrics;
pub mod node;
pub mod omega;
pub mod omega_enhanced;
pub mod p2p;
pub mod performance_monitoring;
pub mod performance_optimizations;
pub mod performance_validation;
pub mod post_quantum_crypto;
pub mod privacy;
pub mod resource_cleanup;
pub mod timing;

pub mod qanto_ai_metrics;
pub mod qanto_compat;
pub mod qanto_native_crypto;
pub mod qanto_net;
pub mod qanto_p2p;
pub mod qanto_serde;
pub mod qanto_storage;
pub mod qantodag;
pub mod saga;
pub mod transaction;
pub mod types;
pub mod wallet;
pub mod websocket_server;
pub mod x_phyrus;
pub mod zkp;

// Conditionally compiled modules for extended features.
#[cfg(feature = "infinite-strata")]
pub mod infinite_strata_node;
#[cfg(feature = "zk")]
pub mod zk;
