apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qanto-node.fullname" . }}-config
  labels:
    {{- include "qanto-node.labels" . | nindent 4 }}
data:
  config.toml: |
    # Qanto Node Configuration
    [network]
    listen_addresses = ["/ip4/0.0.0.0/tcp/{{ .Values.service.ports.p2p }}"]
    {{- if .Values.qanto.bootNodes }}
    boot_nodes = {{ .Values.qanto.bootNodes | toJson }}
    {{- end }}
    
    [rpc]
    bind_address = "0.0.0.0:{{ .Values.service.ports.api }}"
    cors = "{{ .Values.qanto.rpcCors }}"
    
    [websocket]
    bind_address = "0.0.0.0:{{ .Values.service.ports.websocket }}"
    max_connections = {{ .Values.qanto.wsMaxConnections }}
    
    [metrics]
    bind_address = "0.0.0.0:{{ .Values.service.ports.metrics }}"
    enabled = {{ .Values.monitoring.enabled }}
    
    [storage]
    path = "/app/data"
    
    [logging]
    level = "{{ .Values.config.logLevel }}"
    path = "/app/logs"
    
    [consensus]
    network = "{{ .Values.qanto.network }}"