name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenCL
        run: sudo apt-get update && sudo apt-get install -y pocl-opencl-icd opencl-headers

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Check formatting for qanto package
        run: cargo fmt -p qanto -- --check

      - name: Check for common issues (Clippy)
        run: cargo clippy --workspace -- -D warnings

      - name: Build project binaries
        run: cargo build --workspace --verbose

      - name: Run tests
        run: cargo test --workspace --verbose
