name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Check formatting
        run: cargo fmt -p qanto -- --check

      - name: Check for common issues (Clippy)
         run: cargo clippy --workspace -- -D warnings

      - name: Build project binaries (excluding examples)
        run: |
          cargo build --bin qanto --verbose
          cargo build --bin qantowallet --verbose

      - name: Run tests (excluding examples)
        run: cargo test --no-examples --verbose
